import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mr Ali's Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <h1>This is blog layout</h1>
      {children}
      <h1>This is blog layout</h1>
    </div>
  );
};

export default DashboardLayout;
