import SideBar from "@/components/adminDashboard/SideBar/SideBar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mr Ali's Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <SideBar contain={children} /> 
    </div>
  );
};

export default DashboardLayout;
